export const Images = {
  loading: new URL('loading.png', import.meta.url).href,
  error: new URL('error.png', import.meta.url).href,
  address: new URL('address.png', import.meta.url).href,
  auth: new URL('auth.png', import.meta.url).href,
  empty: new URL('empty.png', import.meta.url).href,
  message: new URL('message.png', import.meta.url).href,
  notify: new URL('notify.png', import.meta.url).href,
  order: new URL('order.png', import.meta.url).href,
  product: new URL('product.png', import.meta.url).href,
  search: new URL('search.png', import.meta.url).href,
  tending: new URL('tending.png', import.meta.url).href,
  cart: new URL('cart.png', import.meta.url).href,
  logo: new URL('logo.png', import.meta.url).href,
  paySuccess: new URL('paySuccess.png', import.meta.url).href,
  payError: new URL('payError.png', import.meta.url).href,
  take: new URL('take.png', import.meta.url).href,
  lucky: new URL('lucky.png', import.meta.url).href,
}
